### ISSUE TITLE
IntelliJ loses focus after autocompletion if another floating window is on same workspace

### ISSUE THREAD

**Issue by fdietze** [herbstluftwm/herbstluftwm#1010]
IntelliJ IDEA seems to open tiny floating windows for its auto-completion menus.

Reproduction:
* Open Android-Studio or IntelliJ IDEA
* Open another window (e.g. terminal)
* Make the other window a floating window
* Try to use auto-completion in IntelliJ
* After selection a suggestion from the completion menu, IntelliJ loses focus and you cannot continue to type in the code. You have to refocus the IntelliJ first.

**Comment by tiosgz** [comment]
Sorry I cannot test this, but… try adding a rule for the auto-completion window with `manage=off`; if it doesn’t work then try also `focus=off`.

**Comment by t-wissmann** [comment]
I am not able to reproduce this issue with intellij-idea-community-edition 2:2020.2.1-1 on arch linux. Neither with my configuration nor with the default autostart configuration. Also thee setting `focus_follows_mouse` does not make a difference (sometimes, this is the source of focus stealing issues). Below is a screencast where I try to reproduce it with `focus_follows_mouse` first off, then on:

![intellij-completion-focus](https://user-images.githubusercontent.com/9048813/93687611-3732e000-fabf-11ea-847c-41569f217f1d.gif)

What herbstluftwm version are you running? (output of `herbstclient version`). Can you try to reproduce it in the following setup?

1. download the git repository
2. build hlwm  (`mkdir build && cd build && cmake .. && make`)
3. Run `../valgrind-xephyr.sh` from the build directory. This spawns a nested X window with a hlwm in the default configuration (but possibly with your `panel.sh`, which  shouldn't matter here).

**Comment by fdietze** [comment]
Thank you for your help!

I'm running herbstluftwm: `0.8.3`

After bisecting my rules, it seems to be this line, that reproduces it:
```
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
```

That's a fairly common option:
https://github.com/search?q=%22rule+windowtype%3D%27_NET_WM_WINDOW_TYPE_DIALOG%27+focus%3Don%22&type=code

**Comment by tiosgz** [comment]
Well, then you should find out how to differentiate the pop-up from (1) other dialogs (2) other IJ windows including dialogs.

If it closes before you can `xprop` & click, use `hc rule hook=new_client` & then 
```bash
hc -i rule | while IFS=$'\t' read hook name winid; do
  [ "$name" = 'new_client' ] && [ -n "$winid" ] && xprop -id $winid >> /tmp/hlwmclients
done
```

**Comment by fdietze** [comment]
I managed to `xprop` the **completion** window with `sleep 5; xprop`:

```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 2, 2
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_STATE(ATOM) = 
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		window id # of group leader: 0x260003e
WM_TRANSIENT_FOR(WINDOW): window id # 0x260003e
_NET_WM_PID(CARDINAL) = 3583
WM_CLIENT_MACHINE(STRING) = "gurke"
WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1113, 560
		program specified size: 504 by 513
		window gravity: NorthWest
WM_CLASS(STRING) = "sun-awt-X11-XWindowPeer", "jetbrains-studio"
WM_CLIENT_LEADER(WINDOW): window id # 0x2600005
_NET_WM_NAME(UTF8_STRING) = "win6"
WM_NAME(STRING) = "win6"
```

The other dialog (**file selection**) that should gain focus is this window:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 2, 2
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x3c, 0x5, 0x60, 0x2, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_STATE(ATOM) = 
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		window id # of group leader: 0x260003e
WM_TRANSIENT_FOR(WINDOW): window id # 0x260003e
_NET_WM_PID(CARDINAL) = 3583
WM_CLIENT_MACHINE(STRING) = "gurke"
WM_PROTOCOLS(ATOM): protocols  
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 522, 26
		program specified size: 1516 by 238
		window gravity: NorthWest
WM_CLASS(STRING) = "sun-awt-X11-XWindowPeer", "jetbrains-studio"
WM_CLIENT_LEADER(WINDOW): window id # 0x2600005
_NET_WM_NAME(UTF8_STRING) = "win8"
WM_NAME(STRING) = "win8"
```

The differences are:

```diff
 _NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 2, 2
 _NET_WM_DESKTOP(CARDINAL) = 1
 _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
+_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x3c, 0x5, 0x60, 0x2, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
+XdndAware(ATOM) = BITMAP
 _NET_WM_STATE(ATOM) = 
 WM_HINTS(WM_HINTS):
 		Client accepts input or input focus: False
@@ -11,13 +13,13 @@
 WM_TRANSIENT_FOR(WINDOW): window id # 0x260003e
 _NET_WM_PID(CARDINAL) = 3583
 WM_CLIENT_MACHINE(STRING) = "gurke"
-WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS
+WM_PROTOCOLS(ATOM): protocols  
 _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
 WM_NORMAL_HINTS(WM_SIZE_HINTS):
-		program specified location: 1113, 560
-		program specified size: 504 by 513
+		program specified location: 522, 26
+		program specified size: 1516 by 238
 		window gravity: NorthWest
 WM_CLASS(STRING) = "sun-awt-X11-XWindowPeer", "jetbrains-studio"
 WM_CLIENT_LEADER(WINDOW): window id # 0x2600005
-_NET_WM_NAME(UTF8_STRING) = "win6"
-WM_NAME(STRING) = "win6"
+_NET_WM_NAME(UTF8_STRING) = "win8"
+WM_NAME(STRING) = "win8"
```

How can I ignore the completion window using a hc rule?

btw, in xmonad it's working just fine without configuring anything. Any idea on how they do it?

**Comment by fdietze** [comment]
Here is a commit from i3, which might be relevant:
https://github.com/i3/i3/commit/f5afe2f67e5bfafd8901bc0f5cc72f20b6ceec44
(found that via https://github.com/i3/i3/search?q=java&unscoped_q=java&type=commits)

**Comment by t-wissmann** [comment]
> Thank you for your help!
> 
> I'm running herbstluftwm: `0.8.3`
> 
> After bisecting my rules, it seems to be this line, that reproduces it:
> 
> ```
> hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
> ```
> 
> That's a fairly common option:
> https://github.com/search?q=%22rule+windowtype%3D%27_NET_WM_WINDOW_TYPE_DIALOG%27+focus%3Don%22&type=code

I still can't reproduce this issue, with the default config and the rule you specified. Can you please try to reproduce it in Xephyr? (See description above!)

Where is the connection between the present issue and some kind of dialog whatsoever? Does the "other window" you are refering to in your initial post have to be this file dialog you are talking about?

HLWM already implements the i3 commit you are mentioning.

**Comment by t-wissmann** [comment]
(By the way this is still very likely a hlwm bug, but I first need to find it before I can see how to fix it)

**Comment by fdietze** [comment]
So I managed to run xephyr, but was not able to reproduce it. I also replaced my local `autostart` with the default config, and there I can still reproduce it... I have to dig deeper...

**Comment by t-wissmann** [comment]
Thanks! This looks promising!

**Comment by blarz** [comment]
Was this solved in any way?

**Comment by fdietze** [comment]
Sorry, didn't find the time to look into it again, it is still an issue for me, and probably related to my dotfiles. Currently I'm switching to xmonad to code with IntelliJ because of this problem... :disappointed:.

**Comment by t-wissmann** [comment]
Can you share your entire autostart? The rule for `_NET_WM_WINDOW_TYPE_DIALOG` didn't seem to trigger it (since you said you can't reproduce it in xephyr with default autostart and this rule). Maybe I can then take a look.

**Comment by fdietze** [comment]
It's here: https://github.com/fdietze/dotfiles/blob/master/.config/herbstluftwm/autostart
I'm using it with polybar, and light/dark theme switching with https://github.com/fdietze/dotfiles/blob/master/bin/theme

**Comment by t-wissmann** [comment]
Sorry, but even with your config with intellij-idea-community-edition 4:2020.3.2-1 I can't reproduce it. Can you share a screencast of it such that I can see what you are doing precisely?

**Comment by fdietze** [comment]
So I tried it again. Autocompletion works well now, but the fuzzy file finder dialogs (ctrl+shift+N) are closing as soon as I press a key:

Android Studio 4.1.2


![2021-03-03_11-41-38_2560x1440](https://user-images.githubusercontent.com/1186516/109807872-fa464a00-7c15-11eb-9a7c-7528ae8fcc2d.png)

Then press CTRL+SHIFT+N to open the dialog:

![2021-03-03_11-41-50_2560x1440](https://user-images.githubusercontent.com/1186516/109807907-029e8500-7c16-11eb-94aa-02cb8c282acc.png)

When trying to type, the dialog closes immediately.

**Comment by t-wissmann** [comment]
> You can see in the screenshot that the dialog opens unfocused. Clicking it first to focus and then typing works well.

Per default, every new window is focused (`hc rule focus=on`). Are you overwriting this by other rules? I think the solution is to add another rule that makes the dialog get focused.

**Comment by fdietze** [comment]
True!

I have:

```bash
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on focus=off
```
disabling this, makes the dialogs work. There must have been a reason why I disabled the focus in the first place... :man_shrugging: . I'll see how it goes.

Thank you for your help. It seems like I can properly work with HLWM now.
