### ISSUE TITLE
Urgent window uses “tiling” theme instead of “minimal”

### ISSUE THREAD

**Issue by tiosgz** [herbstluftwm/herbstluftwm#937]
~~I couldn’t reproduce with anything else than Vivaldi, hence the title.~~ Seems to happen also with PCManFM-Qt when navigating folders.

Every time I open a new tab, the window uses `theme.tiling.active` instead of `theme.minimal.active` until I click something or change focus to another window (then it uses `minimal` again). As per what `hc -i` says, it seems the window marks & then unmarks itself (or is marked & unmarked) urgent, if that helps. I seem to have `focus_stealing_prevention` on (though I thought it’s off).

I guess it has something to do with #934 but I’m not sure as I have updated from 0.8.3 or a few commits before.

Do you have any idea what happens or do you want me to try to find out more?

(Also while testing this I’ve had some issues with border width and Firefox but I’ll keep these for later.)

**Comment by tiosgz** [comment]
OK so I finally found a way how to get more info (it was “really difficult” :-P). Urgent client is always decorated as if it was in a non-`max` leaf with more clients even if it’s alone and both `smart_window_surroundings` and `smart_frame_surroundings` are on.

**Comment by t-wissmann** [comment]
> OK so I finally found a way how to get more info (it was “really difficult” :-P). Urgent client is always decorated as if it was in a non-`max` leaf with more clients even if it’s alone and both `smart_window_surroundings` and `smart_frame_surroundings` are on. (Another edit:) Oh, and it keeps this till client switching.

I can't reproduce the issue with pcmanfm and new tubs, but I think I know where it comes from: `Client::setup_border()` is called whenever the urgency state changes, and it calls `Client::getDecTriple()` to find out which child of `theme.` to use, and this only takes the tiling and  fullscreen state of the client into account, but ignores these `smart_window_surroundings` aspects.

I think the fix (and anyway cleaner method) is that the window remembers the `DecTriple` (i.e. the child of the `theme.` object) which has been used last, and uses that when the urgency state changes.

> Edit: also, as a side note, I think a client should be marked urgent only if it’s not active.

I'm not sure about this one, but you're right in the sense that I don't know a single application that sets itself urgent while it's active anyway. The EWMH-Spec is quite vague regarding this:



> _NET_WM_STATE_DEMANDS_ATTENTION indicates that some action in or with the window happened. For example, it may be set by the Window Manager if the window requested activation but the Window Manager refused it, or the application may set it if it finished some work. This state may be set by both the Client and the Window Manager. It should be unset by the Window Manager when it decides the window got the required attention (usually, that it got activated). (https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372536800)

**Comment by tiosgz** [comment]
> I can't reproduce the issue with pcmanfm and new tubs

This happens only with the Qt version when I open/close a folder, and usually blinks only for a short time.
> I think the fix (and anyway cleaner method) is that the window remembers the `DecTriple` (i.e. the child of the `theme.` object) which has been used last, and uses that when the urgency state changes.

I was about to protest ‘What if it changes while it’s urgent?’ (e.g. minimal → tiling) but you were talking about ‘Urgency change only changes between urgent and active/inactive and keeps the rest from its current theme’, right?
> I'm not sure about this one, but you're right in the sense that I don't know a single application that sets itself urgent while it's active anyway. The EWMH-Spec is quite vague regarding this:
> 
> > _NET_WM_STATE_DEMANDS_ATTENTION indicates that some action in or with the window happened. For example, it may be set by the Window Manager if the window requested activation but the Window Manager refused it, or the application may set it if it finished some work. This state may be set by both the Client and the Window Manager. It should be unset by the Window Manager when it decides the window got the required attention (usually, that it got activated). (https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372536800)

If it requests activation and is active, the request is fulfilled. If it marks itself urgent while it’s active, I’d consider this also unnecessary. Unless you plan to track user (in)activity, I’d consider urgent active client a nonsense.

**Comment by t-wissmann** [comment]
> > I can't reproduce the issue with pcmanfm and new tubs
> 
> This happens only with the Qt version when I open/close a folder, and usually blinks only for a short time.

With pacman-qt I'm able to reproduce it by entering a folder.


> > I think the fix (and anyway cleaner method) is that the window remembers the `DecTriple` (i.e. the child of the `theme.` object) which has been used last, and uses that when the urgency state changes.
> 
> I was about to protest ‘What if it changes while it’s urgent?’ (e.g. minimal → tiling) but you were talking about ‘Urgency change only changes between urgent and active/inactive and keeps the rest from its current theme’, right?

Right, these two things can't happen at the same time

> > I'm not sure about this one, but you're right in the sense that I don't know a single application that sets itself urgent while it's active anyway. The EWMH-Spec is quite vague regarding this:
> > > _NET_WM_STATE_DEMANDS_ATTENTION indicates that some action in or with the window happened. For example, it may be set by the Window Manager if the window requested activation but the Window Manager refused it, or the application may set it if it finished some work. This state may be set by both the Client and the Window Manager. It should be unset by the Window Manager when it decides the window got the required attention (usually, that it got activated). (https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372536800)
> 
> If it requests activation and is active, the request is fulfilled. If it marks itself urgent while it’s active, I’d consider this also unnecessary. Unless you plan to track user (in)activity, I’d consider urgent active client a nonsense.

I'm still unsure whether I should agree, because for example, the urgency flag is often used to visualize the terminal bell, which also makes sense if the terminal is focused. But since I don't know any terminal that does that (while it's focused), I think it's a simple and quick fix to solve the issue for you, so let's go for it.

**Comment by tiosgz** [comment]
> I'm still unsure whether I should agree, because for example, the urgency flag is often used to visualize the terminal bell, which also makes sense if the terminal is focused.

I hadn’t thought of that. Right, that makes sense (though I consider the bell a forbidden character :-P).

**Comment by blarz** [comment]
So it really was triggered by #934 and fixed with #940. Thanks for the report!

**Comment by tiosgz** [comment]
> So it really was triggered by #934 and fixed with #940. Thanks for the report!

Err… not really. With #934 I only started seeing urgent windows, which I didn’t before. The theming bug is still present.

**Comment by blarz** [comment]
> > So it really was triggered by #934 and fixed with #940. Thanks for the report!
> 
> Err… not really. With #934 I only started seeing urgent windows, which I didn’t before. The theming bug is still present.

I see, got that wrong then.

**Comment by blarz** [comment]
> smart

Ok I ran into that problem today. I'll see if I can fix it soon.

**Comment by blarz** [comment]
I guess I fixed it with #1017, can you confirm?

**Comment by tiosgz** [comment]
Yes, thank you. Sorry for not letting you know earlier, it took me some time to find out again how to get an urgent client.

**Comment by blarz** [comment]
> Yes, thank you. Sorry for not letting you know earlier, it took me some time to find out again how to get an urgent client.

No worries, I created this PR a couple of hours ago and it just got merged. I wasn't expecting an answer so soon :)

Thank you for the report!
